# Generated by Django 4.2.7 on 2025-09-08 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pw_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1, help_text='Number of tickets purchased'),
        ),
    ]
