# Generated by Django 4.2.7 on 2026-01-07 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pw_website", "0002_ticket_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="price_per_ticket",
        ),
        migrations.AddField(
            model_name="ticket",
            name="price_per_ticket",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="ticket",
            name="ticket_type",
            field=models.CharField(
                choices=[
                    ("normal", "Normal"),
                    ("regular", "Regular"),
                    ("premium", "Premium"),
                    ("vip", "VIP"),
                ],
                default="normal",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="customer_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
