# Generated by Django 4.2.7 on 2026-01-07 11:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pw_website", "0003_remove_event_price_per_ticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of tickets purchased by this customer"
            ),
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("regular", "Regular"),
                            ("premium", "Premium"),
                            ("vip", "VIP"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("quantity", models.PositiveIntegerField()),
                ("description", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="pw_website.event",
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "ticket_type")},
            },
        ),
    ]
