# Generated by Django 4.2.18 on 2026-01-07 12:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("pw_website", "0004_alter_ticket_quantity_tickettype"),
    ]

    operations = [
        migrations.CreateModel(
            name="TicketInventory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ticket_type",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("regular", "Regular"),
                            ("premium", "Premium"),
                            ("vip", "VIP"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "price_per_ticket",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_quantity", models.PositiveIntegerField(default=0)),
                ("remaining_quantity", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_inventory",
                        to="pw_website.event",
                    ),
                ),
            ],
            options={
                "ordering": ["ticket_type"],
                "unique_together": {("event", "ticket_type")},
            },
        ),
        migrations.AlterField(
            model_name="ticket",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, help_text="Number of tickets purchased"
            ),
        ),
        migrations.DeleteModel(
            name="TicketType",
        ),
    ]
